### ISSUE TITLE
Image is not displayed if no markup before

### ISSUE THREAD

**Issue by kursusHC** [PhileCMS/phileInlineImage#1]
Hi, 

Thanks for the nice plugin. 

If no markup is added before the image call, this image is not displayed. 

The following will work :

```
## This is a Sub Page
icon.png
```

The following won't 

```
icon.png
## This is a Sub Page
```

Changing the regex from 

```
$regex = "/(\n<p>) [...]
```

to 

```
$regex = "/(<p>) [...]
```

Solves the thing.

**Comment by james2doyle** [comment]
This is a special case for before or after headers.

It is actually not proper convention to have _no new lines_ after headers, although it still renders. 

Check out this example: 

``` markdown
A simple paragraph.

Icon.png
```

``` html
<p>A simple paragraph.</p>
<p>Icon.png</p>
```

``` markdown
A simple paragraph.
Icon.png
```

``` html
<p>A simple paragraph. Icon.png</p>
```

The second example would require a lot more code to make work with this plugin. You would have to extract the image name and then do the wrapping function. The idea is to make it easy to render images with just the filename alone, by itself. The regex would have to get even more complicated in order to differ between a image name in a regular paragraph and an image name that you are trying to specifically target in order to be wrapped.

**Comment by kursusHC** [comment]
I'm not sure we talk about the same thing. I know it would be over complicated to extract the image name if it is mixed with some other markup. 

Open a new file and fill it with 

```
icon.png
```

It won't work, whatever you add a line-break before or not.

A file with 

```
icon1.png

icon2.png
```

will correctly wrap icon2.png but not icon1.png. But if you remove the line break from the regex it will work.

**Comment by james2doyle** [comment]
Oh I see now. Yeah you are right. Removing the newline is better. I will do it now.

**Comment by james2doyle** [comment]
Do you find the plugin is working well anyway? I havent got too much feedback on it.

**Comment by kursusHC** [comment]
Apart from this it works very well. I think a great improvement would be to turn the plugin (or to fork it) into a general "content wrapper" (ie pass the regex filters - jpg|jpeg|png|etc - into a parameter).

Out of curiosity why isn't it possible to parse the md file before it is rendered ? (ie why  do you have to remove the p tags in the first place ?)

**Comment by james2doyle** [comment]
It is possible to parse the [content before](https://github.com/PhileCMS/Phile/blob/master/lib/Phile/Model/Page.php#L88). But the 2 major parsers (Textile and Markdown) both output HTML. So it is a little more verbose to parse the HTML.

I was thinking of making a "substitute" plugin that would accept regex and then run a function. I need to find the time to develop it. Maybe you can make it? _wink wink_

**Comment by kursusHC** [comment]
All right I'll try to take the time when I'm done with my current project (for which I've set up something that comes close to this general substitution idea).
